id: A6F5E6FDE
title: 'A Drop of Jewels: A Guru Yoga for Lord Gampopa'
type: translation
pechas:
- I0055E693
- I40648C99
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:55:54.269011
  last_modified_at: 2023-01-04 11:55:54.269019
  collections:
  - Gampopa Series
  - Works of Tibetan Masters
alignment_to_base:
  I0055E693/F32B: 5A64
  I40648C99/69BA: 5A64
